rm moveit_setup.aux
rm moveit_setup.bbl
rm moveit_setup.blg
rm moveit_setup.brf
rm moveit_setup.log
rm moveit_setup.out
rm moveit_setup.tex~
rm moveit_setup.tex.backup
rm moveit_setup_bibliography.bib~
rm moveit_setup_bibliography.bib.backup
